# Generated by Django 2.2.12 on 2020-12-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.IntegerField(default=0, verbose_name='Номер аудитории')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('tp', models.CharField(max_length=50, verbose_name='Тип')),
                ('cpu', models.CharField(max_length=50, verbose_name='Процессор')),
                ('gpu', models.CharField(max_length=50, verbose_name='Тип видеокарты')),
                ('ram', models.IntegerField(verbose_name='Объем оперативной памяти, ГБ')),
                ('state', models.CharField(max_length=50, verbose_name='Состояние')),
                ('date', models.DateField(verbose_name='Приобретен')),
                ('use', models.DateField(verbose_name='Введен в эксплуатацию')),
                ('person', models.CharField(max_length=50, verbose_name='Ответветственное лицо')),
                ('term', models.CharField(max_length=50, verbose_name='Срок амортизации')),
            ],
        ),
        migrations.CreateModel(
            name='Repairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rBrand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('rModel', models.CharField(max_length=50, verbose_name='Модель')),
                ('cause', models.CharField(max_length=50, verbose_name='Причина')),
                ('rDate', models.DateField(verbose_name='Дата поступления')),
            ],
        ),
    ]
