# Generated by Django 2.2.12 on 2020-12-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='gpu',
        ),
        migrations.AlterField(
            model_name='repairs',
            name='cause',
            field=models.CharField(max_length=200, verbose_name='Причина'),
        ),
    ]
